import { StrategyFormSchema } from "../form-field-types";

/** `InspectionCalculationForm` schéma (AP-MCE-001 Fáze H §9). */
export const INSPECTION_FORM_SCHEMA: StrategyFormSchema = {
  key: "inspection",
  label: "Kontrola",
  category: "inspection",
  featuresOptional: true,
  subtypeOptions: [
    { value: "visual", label: "Vizuální" },
    { value: "dimensional_manual", label: "Rozměrová (ruční)" },
    { value: "dimensional_cmm", label: "Rozměrová (CMM)" },
    { value: "gauge", label: "Kalibr" },
    { value: "surface_roughness", label: "Drsnost povrchu" },
    { value: "hardness", label: "Tvrdost" },
    { value: "runout", label: "Házení" },
    { value: "balancing", label: "Vyvážení" },
    { value: "pressure_test", label: "Tlaková zkouška" },
    { value: "leak_test", label: "Zkouška těsnosti" },
    { value: "functional_test", label: "Funkční zkouška" },
    { value: "material_certificate_review", label: "Kontrola materiálového atestu" },
    { value: "documentation_review", label: "Kontrola dokumentace" },
    { value: "final_release", label: "Závěrečné uvolnění" },
    { value: "custom_inspection", label: "Vlastní kontrola" },
  ],
  measurementRequirementOptions: [
    { value: "first_piece", label: "První kus" },
    { value: "in_process", label: "Průběžná" },
    { value: "sample", label: "Výběrová" },
    { value: "hundred_percent", label: "100 %" },
    { value: "final_batch", label: "Závěrečná dávka" },
    { value: "document_only", label: "Jen dokumentace" },
  ],
  featureFields: [
    { key: "characteristicCount", group: "feature", label: "Počet znaků na kus", type: "number" },
    { key: "equipmentId", group: "feature", label: "Vybavení (id)", type: "text" },
    { key: "preparationTimeMin", group: "feature", label: "Příprava", type: "number", unit: "min" },
    { key: "measurementTimePerCharacteristicMin", group: "feature", label: "Měření na znak", type: "number", unit: "min" },
    { key: "handlingTimeMin", group: "feature", label: "Manipulace", type: "number", unit: "min" },
    { key: "documentationTimeMin", group: "feature", label: "Dokumentace", type: "number", unit: "min" },
    { key: "reportTimeMin", group: "feature", label: "Protokol", type: "number", unit: "min" },
    { key: "cleanupTimeMin", group: "feature", label: "Úklid", type: "number", unit: "min" },
    { key: "repetitionCount", group: "feature", label: "Počet opakování", type: "number" },
  ],
  operationFields: [
    { key: "workstationId", group: "feature", label: "Pracoviště", type: "text" },
    { key: "inspectionSubtype", group: "feature", label: "Výchozí podtyp (bez featurů)", type: "text" },
    { key: "samplingPlan", group: "feature", label: "Sampling plán (výchozí)", type: "text" },
    { key: "sampleSize", group: "feature", label: "Velikost vzorku", type: "number" },
    { key: "samplingFrequency", group: "feature", label: "Frekvence vzorkování", type: "number" },
    { key: "firstPieceInspection", group: "feature", label: "Kontrola prvního kusu", type: "checkbox" },
    { key: "inProcessInspection", group: "feature", label: "Průběžná kontrola", type: "checkbox" },
    { key: "finalInspection", group: "feature", label: "Závěrečná kontrola", type: "checkbox" },
    { key: "inspectionEquipmentIds", group: "feature", label: "Výchozí vybavení (id, čárkami)", type: "text" },
    { key: "preparationTimeMin", group: "feature", label: "Příprava (operace)", type: "number", unit: "min" },
    { key: "setupTimeMin", group: "feature", label: "Seřízení", type: "number", unit: "min" },
    { key: "measurementTimePerCharacteristicMin", group: "feature", label: "Měření na znak (výchozí)", type: "number", unit: "min" },
    { key: "characteristicCount", group: "feature", label: "Počet znaků (výchozí)", type: "number" },
    { key: "partHandlingTimeMin", group: "feature", label: "Manipulace s dílem", type: "number", unit: "min" },
    { key: "documentationTimeMin", group: "feature", label: "Dokumentace (operace)", type: "number", unit: "min" },
    { key: "reportTimeMin", group: "feature", label: "Protokol (operace)", type: "number", unit: "min" },
    { key: "cleanupTimeMin", group: "feature", label: "Úklid (operace)", type: "number", unit: "min" },
    { key: "programCreationTimeMin", group: "feature", label: "Tvorba CMM programu", type: "number", unit: "min" },
    { key: "programLoadTimeMin", group: "feature", label: "Načtení programu", type: "number", unit: "min" },
    { key: "fixtureSetupTimeMin", group: "feature", label: "Upnutí do přípravku", type: "number", unit: "min" },
    { key: "automaticCycleTimePerCharacteristicMin", group: "feature", label: "Automatický cyklus na znak", type: "number", unit: "min" },
    { key: "operatorAttendanceTimePerCharacteristicMin", group: "feature", label: "Obsluha na znak", type: "number", unit: "min" },
    { key: "evaluationTimePerCharacteristicMin", group: "feature", label: "Vyhodnocení na znak", type: "number", unit: "min" },
    { key: "fixedAllowanceMin", group: "feature", label: "Fixní přirážka", type: "number", unit: "min" },
    { key: "percentageAllowance", group: "feature", label: "Procentní přirážka", type: "number", unit: "%" },
  ],
};
