import { StrategyFormSchema } from "../form-field-types";

/** `ManualOperationCalculationForm` schéma (AP-MCE-001 Fáze H §9). */
export const MANUAL_FORM_SCHEMA: StrategyFormSchema = {
  key: "manual",
  label: "Ruční operace",
  category: "manual",
  featuresOptional: true,
  subtypeOptions: [
    { value: "deburring", label: "Odjehlení" },
    { value: "hand_grinding", label: "Ruční broušení" },
    { value: "polishing", label: "Leštění" },
    { value: "cleaning", label: "Čištění" },
    { value: "washing", label: "Mytí" },
    { value: "marking", label: "Značení" },
    { value: "packing", label: "Balení" },
    { value: "unpacking", label: "Vybalení" },
    { value: "manual_drilling", label: "Ruční vrtání" },
    { value: "manual_tapping", label: "Ruční závitování" },
    { value: "straightening", label: "Rovnání" },
    { value: "fitting", label: "Přizpůsobení/lícování" },
    { value: "simple_assembly", label: "Jednoduchá montáž" },
    { value: "disassembly", label: "Demontáž" },
    { value: "preparation", label: "Příprava" },
    { value: "handling", label: "Manipulace" },
    { value: "custom_manual", label: "Vlastní ruční úkon" },
  ],
  measurementRequirementOptions: [
    { value: "none", label: "Žádné" },
    { value: "first_piece", label: "První kus" },
    { value: "every_piece", label: "Každý kus" },
    { value: "sampling", label: "Namátkově" },
  ],
  featureFields: [
    { key: "quantityBasis", group: "feature", label: "Vztaženo k", type: "select", options: [
      { value: "per_piece", label: "Na kus" },
      { value: "per_batch", label: "Na dávku" },
      { value: "per_order", label: "Na zakázku" },
      { value: "per_occurrence", label: "Na výskyt" },
    ] },
    { key: "timeBasis", group: "feature", label: "Zdroj času", type: "select", options: [
      { value: "explicit", label: "Explicitní čas" },
      { value: "template", label: "Standard/šablona" },
      { value: "historical_average", label: "Historický průměr" },
      { value: "rule_based", label: "Pravidlo" },
      { value: "standard_time", label: "Normovaný čas" },
    ] },
    { key: "baseTimeMin", group: "feature", label: "Základní čas", type: "number", unit: "min" },
    { key: "repetitionCount", group: "feature", label: "Počet opakování", type: "number" },
    { key: "employeeQualificationId", group: "feature", label: "Kvalifikace obsluhy (id)", type: "text" },
    { key: "toolOrEquipmentId", group: "feature", label: "Nástroj/vybavení (id)", type: "text" },
    { key: "workstationRequirement", group: "feature", label: "Požadavek na pracoviště", type: "text" },
    { key: "ergonomicDemand", group: "feature", label: "Ergonomická náročnost", type: "select", options: [
      { value: "low", label: "Nízká" },
      { value: "medium", label: "Střední" },
      { value: "high", label: "Vysoká" },
    ] },
    { key: "complexityLevel", group: "feature", label: "Náročnost", type: "select", options: [
      { value: "low", label: "Nízká" },
      { value: "medium", label: "Střední" },
      { value: "high", label: "Vysoká" },
    ] },
  ],
  operationFields: [
    { key: "workstationId", group: "feature", label: "Pracoviště", type: "text" },
    { key: "manualOperationSubtype", group: "feature", label: "Výchozí podtyp (bez featurů)", type: "text" },
    { key: "employeeQualificationId", group: "feature", label: "Kvalifikace obsluhy (id)", type: "text" },
    { key: "productionSeriality", group: "feature", label: "Sériovost výroby", type: "select", options: [
      { value: "single_piece", label: "Kusová" },
      { value: "small_batch", label: "Malosériová" },
      { value: "medium_batch", label: "Středněsériová" },
      { value: "large_batch", label: "Velkosériová" },
      { value: "mass_production", label: "Hromadná výroba" },
    ] },
    { key: "batchSize", group: "feature", label: "Velikost dávky", type: "number" },
    { key: "setupTimeMin", group: "feature", label: "Příprava/seřízení", type: "number", unit: "min" },
    { key: "preparationTimeMin", group: "feature", label: "Příprava pracoviště", type: "number", unit: "min" },
    { key: "handlingTimePerPieceMin", group: "feature", label: "Manipulace na kus", type: "number", unit: "min" },
    { key: "auxiliaryTimePerPieceMin", group: "feature", label: "Pomocný čas na kus", type: "number", unit: "min" },
    { key: "cleanupTimeMin", group: "feature", label: "Úklid", type: "number", unit: "min" },
    { key: "firstPieceTimeMin", group: "feature", label: "První kus navíc", type: "number", unit: "min" },
    { key: "interBatchTimeMin", group: "feature", label: "Mezi dávkami", type: "number", unit: "min" },
    { key: "waitingTimeMin", group: "feature", label: "Čekání", type: "number", unit: "min" },
    { key: "fixedAllowanceMin", group: "feature", label: "Fixní přirážka", type: "number", unit: "min" },
    { key: "percentageAllowance", group: "feature", label: "Procentní přirážka", type: "number", unit: "%" },
    { key: "ergonomicCoefficient", group: "feature", label: "Ergonomický koeficient", type: "number" },
    { key: "fatigueCoefficient", group: "feature", label: "Koeficient únavy", type: "number" },
    { key: "workplaceCoefficient", group: "feature", label: "Koeficient pracoviště", type: "number" },
  ],
};
