import { StrategyFormSchema } from "../form-field-types";

/** `MillingCalculationForm` schéma (AP-MCE-001 Fáze H §7). */
export const MILLING_FORM_SCHEMA: StrategyFormSchema = {
  key: "milling",
  label: "Frézování",
  category: "milling",
  subtypeOptions: [
    { value: "face_milling", label: "Srovnání roviny" },
    { value: "pocket_milling", label: "Kapsa" },
    { value: "contour_milling", label: "Kontura" },
    { value: "slot_milling", label: "Drážka" },
    { value: "drilling", label: "Vrtání" },
    { value: "countersinking", label: "Zahlubování" },
    { value: "reaming", label: "Vystružování" },
    { value: "threading", label: "Závitování" },
    { value: "two_d", label: "2D dráha" },
    { value: "two_and_half_d", label: "2.5D dráha" },
    { value: "three_d", label: "3D (aproximace)" },
    { value: "custom_path", label: "Vlastní dráha" },
  ],
  machiningModeOptions: [
    { value: "roughing", label: "Hrubování" },
    { value: "semi_finishing", label: "Předdokončení" },
    { value: "finishing", label: "Dokončení" },
  ],
  measurementRequirementOptions: [
    { value: "none", label: "Žádné" },
    { value: "first_piece", label: "První kus" },
    { value: "every_piece", label: "Každý kus" },
    { value: "sampling", label: "Namátkově" },
  ],
  featureFields: [
    { key: "pathLengthMm", group: "geometry", label: "Délka dráhy", type: "number", unit: "mm", appliesToSubtypes: ["two_d", "two_and_half_d", "three_d", "custom_path"] },
    { key: "areaLengthMm", group: "geometry", label: "Délka plochy", type: "number", unit: "mm", appliesToSubtypes: ["face_milling", "three_d"] },
    { key: "areaWidthMm", group: "geometry", label: "Šířka plochy", type: "number", unit: "mm", appliesToSubtypes: ["face_milling", "three_d"] },
    { key: "pocketLengthMm", group: "geometry", label: "Délka kapsy", type: "number", unit: "mm", appliesToSubtypes: ["pocket_milling"] },
    { key: "pocketWidthMm", group: "geometry", label: "Šířka kapsy", type: "number", unit: "mm", appliesToSubtypes: ["pocket_milling"] },
    { key: "pocketDepthMm", group: "geometry", label: "Hloubka kapsy", type: "number", unit: "mm", appliesToSubtypes: ["pocket_milling"] },
    { key: "contourLengthMm", group: "geometry", label: "Délka kontury", type: "number", unit: "mm", appliesToSubtypes: ["contour_milling"] },
    { key: "slotLengthMm", group: "geometry", label: "Délka drážky", type: "number", unit: "mm", appliesToSubtypes: ["slot_milling"] },
    { key: "slotWidthMm", group: "geometry", label: "Šířka drážky", type: "number", unit: "mm", appliesToSubtypes: ["slot_milling"] },
    { key: "machiningDepthMm", group: "geometry", label: "Hloubka obrábění", type: "number", unit: "mm" },
    { key: "stockAllowanceRadialMm", group: "geometry", label: "Přídavek radiální", type: "number", unit: "mm" },
    { key: "stockAllowanceAxialMm", group: "geometry", label: "Přídavek axiální", type: "number", unit: "mm" },
    { key: "approachLengthMm", group: "geometry", label: "Nájezd", type: "number", unit: "mm" },
    { key: "retractLengthMm", group: "geometry", label: "Výjezd", type: "number", unit: "mm" },
    { key: "peckDepthMm", group: "geometry", label: "Hloubka pecku", type: "number", unit: "mm", appliesToSubtypes: ["drilling", "countersinking", "reaming"] },
    { key: "holeCount", group: "geometry", label: "Počet otvorů", type: "number", appliesToSubtypes: ["drilling", "countersinking", "reaming", "threading"] },
    { key: "threadPitchMm", group: "geometry", label: "Stoupání závitu", type: "number", unit: "mm", appliesToSubtypes: ["threading"] },

    { key: "cuttingSpeedMMin", group: "cuttingConditionOverride", label: "Řezná rychlost (přepis)", type: "number", unit: "m/min" },
    { key: "feedPerToothMm", group: "cuttingConditionOverride", label: "Posuv na zub (přepis)", type: "number", unit: "mm" },
    { key: "feedRateMmMin", group: "cuttingConditionOverride", label: "Posuvová rychlost (přepis)", type: "number", unit: "mm/min" },
    { key: "spindleSpeedRpm", group: "cuttingConditionOverride", label: "Otáčky (přepis)", type: "number", unit: "min⁻¹" },
    { key: "toolDiameterMm", group: "cuttingConditionOverride", label: "Průměr nástroje (přepis)", type: "number", unit: "mm" },
    { key: "teethCount", group: "cuttingConditionOverride", label: "Počet zubů (přepis)", type: "number" },

    { key: "passCount", group: "passStrategy", label: "Počet průchodů (explicitní)", type: "number" },
    { key: "stepOverMm", group: "passStrategy", label: "Stepover", type: "number", unit: "mm" },
    { key: "stepDownMm", group: "passStrategy", label: "Stepdown", type: "number", unit: "mm" },

    { key: "widthOfCutMm", group: "feature", label: "Radiální záběr (ae)", type: "number", unit: "mm" },
    { key: "depthOfCutMm", group: "feature", label: "Axiální záběr (ap)", type: "number", unit: "mm" },
    { key: "toolProfileId", group: "feature", label: "Nástroj (id profilu)", type: "text" },
    { key: "dwellTimeSec", group: "feature", label: "Prodleva (dwell)", type: "number", unit: "s" },
    { key: "plannedToolChanges", group: "feature", label: "Plánované výměny nástroje (přepis)", type: "number" },
    { key: "coolantMode", group: "feature", label: "Chlazení", type: "text" },
    { key: "interruptedCut", group: "feature", label: "Přerušovaný řez", type: "checkbox" },
    { key: "adaptiveClearing", group: "feature", label: "Adaptivní/trochoidní dráha", type: "checkbox" },
  ],
  operationFields: [
    { key: "workstationId", group: "feature", label: "Pracoviště", type: "text" },
    { key: "batchSize", group: "feature", label: "Velikost dávky", type: "number" },
    { key: "setupTimeMin", group: "feature", label: "Seřízení", type: "number", unit: "min" },
    { key: "handlingTimePerPieceMin", group: "feature", label: "Manipulace na kus", type: "number", unit: "min" },
    { key: "measurementTimePerPieceMin", group: "feature", label: "Měření na kus", type: "number", unit: "min" },
    { key: "firstPieceInspectionTimeMin", group: "feature", label: "Kontrola prvního kusu", type: "number", unit: "min" },
    { key: "finalInspectionTimeMin", group: "feature", label: "Závěrečná kontrola", type: "number", unit: "min" },
    { key: "fixedAllowanceMin", group: "feature", label: "Fixní přirážka", type: "number", unit: "min" },
    { key: "percentageAllowance", group: "feature", label: "Procentní přirážka", type: "number", unit: "%" },
    { key: "clampingCount", group: "feature", label: "Počet upnutí operace", type: "number" },
    { key: "fixtureChangeCount", group: "feature", label: "Počet přeupnutí", type: "number" },
  ],
};
